# version: '3.8'

services:
  vault-management-panel:
    container_name: vault-management-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
      - FIREBASE_ADMIN_PRIVATE_KEY=${FIREBASE_ADMIN_PRIVATE_KEY}
      - FIREBASE_ADMIN_CLIENT_EMAIL=${FIREBASE_ADMIN_CLIENT_EMAIL}
      - FIREBASE_ADMIN_PROJECT_ID=${FIREBASE_ADMIN_PROJECT_ID}
      - FIREBASE_ADMIN_PRIVATE_KEY_ID=${FIREBASE_ADMIN_PRIVATE_KEY_ID}
      - FIREBASE_ADMIN_TOKEN_URI=${FIREBASE_ADMIN_TOKEN_URI}
      - FIREBASE_ADMIN_AUTH_PROVIDER_CERT_URL=${FIREBASE_ADMIN_AUTH_PROVIDER_CERT_URL}
      - FIREBASE_ADMIN_CLIENT_CERT_URL=${FIREBASE_ADMIN_CLIENT_CERT_URL}
    ports:
      - "3001:3000"
    networks:
      - app-network

networks:
  app-network:
